name: release-k8s-charm
base: core22

version: "1.0"
summary: A tool to ease releasing Kubernetes operator charms to charmhub
description: |
  A charmhub release creation utility for Kubernetes operator charms: packs the charm, uploads the OCI images for the charm to Canonical's OCI registry, uploads the charm, releases.

  Usage: `release-k8s-charm --charm-metadata [path-to-charm-metadata.yaml]`

grade: stable
confinement: strict
architectures:
  - amd64
  - arm64

apps:
  release-k8s-charm:
    command: release-k8s-charm
    plugs: [home, network]

parts:
  release-k8s-charm:
    plugin: dump
    source: .
    source-type: local
    override-build: |
      cp release_k8s_charm/main.py $SNAPCRAFT_PART_INSTALL/release-k8s-charm
    stage-packages:
      - python3-yaml
